version: '3'
services:
#  frontend:
#    build: ./frontend
#    container_name: san-2024-fe

  backend:
    build: ./backend
    container_name: san-2024-be
    restart: always
    ports:
      - 7004:3000
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=san_2024
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=san2024jwt
    volumes:
      - ./backend/public/uploads:/app/public/uploads

  db:
    container_name: postgres-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - 7003:5432

volumes:
  db_data:
    driver: local
