version: "3"
services:
  frontend:
    build: ./frontend
    container_name: san-2025-fe
    ports:
      - 7005:7005
    networks:
      - san-2025-network
  backend:
    build: ./backend
    container_name: san-2025-be
    restart: always
    ports:
      - 7004:3000
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - BASE_URL=https://dev.api.socialdance.id
      - APP_PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=san_2025
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=san2025jwt
    networks:
      - san-2025-network
    volumes:
      - ./backend/public/uploads:/app/public/uploads

  db:
    container_name: postgres-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - 7003:5432
    networks:
      - san-2025-network

networks:
  san-2025-network:
    driver: bridge

volumes:
  db_data:
    driver: local
